# Generated by Django 5.1.5 on 2025-03-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customer_birth_customer_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='rating',
        ),
    ]
