# Generated by Django 5.1.5 on 2025-02-17 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('users', '0003_remove_customer_birth_customer_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('service_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
